### ISSUE TITLE
On Firefox down

### ISSUE THREAD

**Issue by Popcorn13** [iridium1-waze/WME-P2SM#4]
Hey

Not working on Firefox (86.0) any more. Only P2SM & Toolbox active. (Adblocker etc. are deactivated)

Regards
Andy_Na

**Comment by iridium1-waze** [comment]
Hallo Andy. 
Danke dir für Info, ist mir schon bekannt. 
Ich vermute, du nutzt die aktuellste Version von FF (Quantum), bei der einiges unter der Haube geändert wurde, speziell die Behandlung von "alten" Add-Ons und einige neue Sicherheitsfeatures.
P2SM ist derzeit nicht das einige Script, dass damit Probleme hat: (Beispiel Lane Tools)

Ich gucke mal, was ich in Erfahrung bringen kann, um das zu lösen,

**Comment by Popcorn13** [comment]
Nutze FF nur im Geschäft.
Das andere Scripte nicht laufen ist mir noch nicht aufgefallen.
Danke für die Info.
